### PR TITLE
Add Proxy support. Fixes #25

### LINKED ISSUE #25: Add Proxy support

### PR DESCRIPTION
**Pull request by mew1033**

### CODE REVIEW

**Comment by basepi** [comment]
Looks good. Has it been tested?

**Comment by mew1033** [comment]
Not yet. @zxjinn, mind testing this?

**Comment by zxjinn** [comment]
I don't believe I'll have time for at least a few weeks now. See if you can find another guinea 🐷 , otherwise I can do it later.

**Comment by mew1033** [comment]
@basepi Okay, I just tested it. Seems like it works. 👍

**Pull request merged**
