### PR TITLE
Ability to disable SSL in splunk forwarders

### PR DESCRIPTION
**Pull request by zxjinn**
Thanks @scottjpack for the original code, CC @mew1033 

An updated pillar would look like this for Nova:

``` yaml
nova:
  returner:
    splunk:
      token: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
      indexer: splunk-indexer.domain.tld
      sourcetype: hubble_audit
      index: hubble
      hec_ssl: False
```

Would you like me to update the pillar.example file with the new additions?

### CODE REVIEW

**Comment by zxjinn** [comment]
I was able to test this with the three possible situations:
- `hec_ssl` defined in pillar as False
- `hec_ssl` defined in pillar as True
- `hec_ssl` not defined in pillar

All three of the scenarios worked as expected.

**Comment by mew1033** [comment]
I think it'd be good to also have proxy support. Do we want to do that here, or just file a separate issue?

**Comment by zxjinn** [comment]
I vote for a new issue for proxy support, but I do think that's a very good suggestion

**Comment by basepi** [comment]
I think @dmcteer wants to discuss this with your team before we merge. So we're going to hold off for the moment.

**Pull request merged**
